FROM registry.access.redhat.com/ubi9/nodejs-22@sha256:ab6c06c0109862fc7da56f9acdc6df35d06da08df0c301f4f0b931d07ac6c494 as console-plugin-builder

USER root

WORKDIR /src/yarn

# Copy the yarn installation folder
COPY yarn-install .

# Install yarn
RUN npm install --offline && \
    ln -s $PWD/node_modules/yarn/bin/yarn /usr/local/bin/yarn && \
    \
    # Show node and yarn versions
    node --version && \
    yarn --version

RUN dnf install nginx -y

RUN yarn config set network-concurrency 1 && \
    yarn config set network-timeout 100000

RUN mkdir -p /var/cache/nginx /var/log/nginx /run && \
    chmod -R 777 /var/cache/nginx /var/log/nginx /run /usr/share/nginx/html/

WORKDIR /usr/src/app

COPY ./kuadrant-console-plugin/package.json ./kuadrant-console-plugin/yarn.lock ./

RUN ls -la

RUN yarn clean
RUN rm -rf ./node_modules
RUN yarn install --production --offline --ignore-optional --frozen-lockfile

RUN ls -la

COPY kuadrant-console-plugin/ .

RUN yarn downstream-replacements --offline
RUN yarn build

RUN pwd && ls -la
RUN ls -la ./dist

RUN cp -r ./dist/* /usr/share/nginx/html/

COPY entrypoint.sh /usr/share/nginx/html/entrypoint.sh

RUN test -f /usr/share/nginx/html/plugin-manifest.json && \
    test -f /usr/share/nginx/html/entrypoint.sh && \
    test -d /usr/share/nginx/html/locales && \
    echo "All required files are present."

LABEL version="0.0.18" \
    com.redhat.component="rhcl-console-plugin-container" \
    name="rhcl-1/rhcl-console-plugin-rhel9" \
    summary="Red Hat Connectivity Link Console Plugin" \
    description="Red Hat Connectivity Link Console Plugin" \
    io.k8s.display-name="Red Hat Connectivity Link Console Plugin" \
    io.openshift.tags="api" \
    maintainer="jmadigan@redhat.com" 


USER 1001
ENTRYPOINT ["/usr/share/nginx/html/entrypoint.sh"]