# Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS builder-runner
RUN microdnf install -y skopeo jq python3 python3-pip
RUN . /cachi2/cachi2.env && \
    echo "Listing contents of /cachi2/output/deps/pip:" && \
    ls -l /cachi2/output/deps/pip && \
    echo "Listing tar.gz files in /cachi2/output/deps/pip:" && \
    ls -l /cachi2/output/deps/pip/*.tar.gz && \
    pip3 install /cachi2/output/deps/pip/ruamel.yaml-0.17.9.tar.gz

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner AS builder

COPY bundle-hack .
COPY limitador-operator/bundle/manifests /manifests/
COPY limitador-operator/bundle/metadata /metadata/

RUN chmod +x ./update_bundle.sh && ./update_bundle.sh

FROM scratch

# Core bundle labels.
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=limitador-operator
LABEL operators.operatorframework.io.bundle.channels.v1=alpha
LABEL operators.operatorframework.io.bundle.channel.default.v1=alpha

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

LABEL com.redhat.component="limitador-operator-bundle" \
      name="Limitador Operator Bundle" \
      release="0.0.1" \
      url="registry.redhat.io/rhcl-1/limitador-operator-bundle" \
      summary="Limitador Operator provides an easy way to install Limitador, providing configurability options at the time of installation." \
      description="Limitador Operator provides an easy way to install Limitador, providing configurability options at the time of installation." \
      io.k8s.description="" \
      io.k8s.display-name="Limitador Operator metadata" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY limitador-operator/bundle/tests/scorecard /tests/scorecard/